# http://module-build.sourceforge.net/META-spec.html
name:         Symbol-Glob
version:      0.03
version_from: lib/Symbol/Glob.pm
installdirs:  site
requires:
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
